export const CONFIG_UPDATE_ROAD = "CONFIG_UPDATE_ROAD";
export const CONFIG_UPDATE_TYPE = "CONFIG_UPDATE_TYPE";

export const DATA_BOUNDS_CHANGED = "DATA_BOUNDS_CHANGED";
export const DATA_LOAD_START = "DATA_START_LOAD";
export const DATA_LOAD_FULFILLED = "DATA_LOAD_FULFILLED";
export const DATA_LOAD_REJECTED = "DATA_LOAD_REJECTED";